
ALTER TABLE FW_CONTROLLER ADD SESSION_CHECK_YN varchar(50);
ALTER TABLE FW_CONTROLLER ADD AUTH varchar(50);

UPDATE FW_CONTROLLER SET [SESSION_CHECK_YN] = 'N', [AUTH] = '' WHERE [ID] IN ('login','loginView');
UPDATE FW_CONTROLLER SET [SESSION_CHECK_YN] = 'Y', [AUTH] = '' WHERE [ID] = 'emp00110';
UPDATE FW_CONTROLLER SET [SESSION_CHECK_YN] = 'Y', [AUTH] = 'A0' WHERE [ID] = 'emp00120';

UPDATE FW_SQL SET SQL = 'SELECT
[ID]
, CLASS_NAME
, METHOD_NAME
, SESSION_CHECK_YN
, AUTH
FROM FW_CONTROLLER
WHERE ID = [ID]
'
WHERE [ID] = 'MASTERCONTROLLERD_01';

DROP TABLE BZ_ID;

CREATE TABLE BZ_ID (
[USR_ID] varchar(50) PRIMARY KEY
, PIN varchar(50)
, AUTH varchar(50)
, FAIL_CNT varchar(50)
, LAST_LOGIN_DTM varchar(50)
);


INSERT INTO BZ_ID values (
'id_A0'
, 'abcd1111'
, 'A0'
, '0'
, ''
);

INSERT INTO BZ_ID values (
'id_U0'
, 'abcd1111'
, 'U0'
, '0'
, ''
);

DELETE FROM FW_SQL WHERE [ID] IN ('LOGIND_01','LOGIND_02','LOGIND_03');

INSERT INTO FW_SQL values (
'LOGIND_01'
, 'SELECT 
USR_ID
, PIN
, AUTH
, FAIL_CNT
, LAST_LOGIN_DTM 
FROM 
BZ_ID
WHERE USR_ID = [USR_ID] 
');

INSERT INTO FW_SQL values (
'LOGIND_02'
, 'UPDATE BZ_ID
SET FAIL_CNT = FAIL_CNT + 1
WHERE USR_ID = [USR_ID] 
');

INSERT INTO FW_SQL values (
'LOGIND_03'
,'UPDATE BZ_ID
SET FAIL_CNT = 0
, LAST_LOGIN_DTM = [LAST_LOGIN_DTM]
WHERE USR_ID = [USR_ID]
');